global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "microservices"
    static_configs:
      - targets:
          ["auth-service:3000", "order-service:3001", "inventory-service:3002"]

  - job_name: "auth-service"
    static_configs:
      - targets: ["auth-service:3000"]

  - job_name: "order-service"
    static_configs:
      - targets: ["order-service:3001"]
